apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: default
spec:
  restartPolicy: Never
  volumes:
  - name: nginx-config
    hostPath:
      path: /etc/nginx
  - name: nginx-content
    hostPath:
      path: /var/www/html
  containers:
  - name: my-nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx
    - name: nginx-content
      mountPath: /var/www/html
